apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sqlite-web.fullname" . }}
  labels:
    {{- include "sqlite-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sqlite-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sqlite-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: data
          hostPath:
            path: {{ .Values.persistence.hostPath }}